fix includes
I'm reshuffling some includes, and once this one stops getting the
sysrepo-cpp headers indirectly via Nacm.h, it fails to build:

 In file included from /home/jkt/work/cesnet/gerrit/CzechLight/rousette/src/restconf/Server.cpp:18:
 /home/jkt/work/cesnet/gerrit/CzechLight/rousette/src/restconf/NotificationStream.h:36:22: error: field has incomplete type 'sysrepo::Session'
    36 |     sysrepo::Session m_session;
       |                      ^
 /home/jkt/work/prog/_build/czechlight-clang17-asan-ubsan/target/include/sysrepo-cpp/Subscription.hpp:24:7: note: forward declaration of 'sysrepo::Session'
    24 | class Session;
       |       ^

Since sysrepo::Session is a member, a forward is not enough.

Change-Id: I6f1b6cb6ddffe20e48a9c1d7953450f7934af161